import type { Metadata } from "next";

import "./globals.css";
import { gilroy, gropled } from "./fonts";
import AllAbsolute from "@/components/sections/absolute/all-absolute";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${gropled.variable} ${gilroy.variable}`}>
        <AllAbsolute />
        {children}
      </body>
    </html>
  );
}
